
//LOGUEAR UN USUARIO
export const FETCH_USUARIO_REQUEST = 'FETCH_USUARIO_REQUEST'
export const FETCH_USUARIO_SUCCESS = 'FETCH_USUARIO_SUCCESS'



//VER PUBLICACIONES

export const VER_PUBLICACIONES_SUCCESS = 'VER_PUBLICACIONES_SUCCESS' 
